### ISSUE TITLE
Provide JS project boilerplate

### ISSUE THREAD

**Issue by thisismydesign** [c-hive/guides#10]
Including:
- https://github.com/c-hive/guides/blob/master/react/way-of-working.md (no react-specific things though)
- https://github.com/c-hive/guides/blob/master/node/way-of-working.md
- vscode settings
  - https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions

**Comment by gomorizsolt** [comment]
This has already been resolved by [**c-hive/js-boilerplate**](https://github.com/c-hive/js-boilerplate), right?

**Comment by thisismydesign** [comment]
Good point, thanks!
