### ISSUE TITLE
Firebase best practices

### ISSUE THREAD

**Issue by thisismydesign** [c-hive/guides#15]
Let's create a `Firebase / Miscellaneous` doc with best practices, including:
- https://gitlab.com/c-hive/firebase-paypal/merge_requests/3#note_172773804
- https://gitlab.com/c-hive/firebase-paypal/issues/4

Same format as https://github.com/c-hive/guides/blob/cefa90fdd6c8cec9ac87ef23cfc0871a7fdc5b7a/js/error-handling.md#best-practices-and-anti-patterns

@gomorizsolt could you take care of this?

**Comment by gomorizsolt** [comment]
Resolved by #16.
